name: Output Event Details
on:
  issues:
    types: opened
jobs:
  issue-details:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          echo "${{ toJson(github.event.repository.issue_comment_url) }}"
          echo "${{ toJson(github.event.repository.issue_events_url) }}"
          echo "${{ toJson(github.event.repository.issues_url) }}"
