name: Output Event Details
on:
  issues:
    types: opened
jobs:
  issue-details:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          echo "Event details:\n ${{ toJson(github.event) }}"
