name: Output Event Details
on:
  issues:
    types: opened
jobs:
  issue-details:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        env:
          EVENT: ${{ toJson(github.event) }}
        run: |
          echo "Event details: $EVENT"
